# Use the official Node.js image
FROM oven/bun:latest

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json or yarn.lock
COPY ./package*.json ./

# Install dependencies
RUN bun install

# Copy the rest of the application files
COPY . .

# Build the Next.js project for production
RUN bun run build

# Expose the desired port
EXPOSE 3000

# Start the application
CMD ["bun", "run", "start"]
